const Map<String, String> appLanguages = {
  'auto': 'Auto-Detect',
  'none': 'Original Source (Transcription)',
  'en': 'English (en)',
  'es': 'Spanish (es)',
  'fr': 'French (fr)',
  'de': 'German (de)',
  'zh': 'Chinese (zh)',
  'ja': 'Japanese (ja)',
  'ko': 'Korean (ko)',
  'ru': 'Russian (ru)',
  'pt': 'Portuguese (pt)',
  'it': 'Italian (it)',
  'ar': 'Arabic (ar)',
  'hi': 'Hindi (hi)',
  'nl': 'Dutch (nl)',
  'tr': 'Turkish (tr)',
  'vi': 'Vietnamese (vi)',
  'pl': 'Polish (pl)',
  'id': 'Indonesian (id)',
  'th': 'Thai (th)',
  'bn': 'Bengali (bn)',
};
